apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "common.labels" . | nindent 6 }} #nindent: n là xuống dòng, indent 6 là cách 6 ký tự
spec:
  replicas: 3
  selector:
    matchLabels: {{ include "common.labels" . | nindent 8 }}
  template:
    metadata:
      labels: {{ include "common.labels" . | nindent 10 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        env:
          - name: ENVVAR1
            value: {{ .Values.value1 }}
          - name: ENVVAR2
            value: {{ .Values.value2 }}
        ports:
        - containerPort: {{ .Values.port }}