apiVersion: v1 # apiVersion tương ứng với kind, mỗi kind (loại resources) có mỗi cái apiVersion khác nhau
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector: {{ include "common.labels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodeport }}
  type: NodePort